#+TITLE: Readme
#+AUTHOR: Zastian Pretorius

* README
This is a simple project to help sort your files on Linux written in c++.
* Install
1. Copy the repo
    #+BEGIN_SRC
    git clone https://github.com/ZastianPretorius/fsorter.git
    #+END_SRC
2. cd into  the fsorter folder
    #+BEGIN_SRC
    cd fsorter
    #+END_SRC
3. Generate a make files
    #+BEGIN_SRC
    cmake .
    #+END_SRC
4. Compile the project
   #+BEGIN_SRC
   make
   #+END_SRC
5. install the project (will require sudo)
   #+BEGIN_SRC
   sudo make install
   #+END_SRC
* Usage
1. cd to the desired location for example
   #+BEGIN_SRC
   cd ~/Downloads
   #+END_SRC
2. Run fsorter.
   #+BEGIN_SRC
   fsorter
   #+END_SRC
3. The first time you run the program nothing will happen but a default settings.toml will be generated found in
   #+BEGIN_SRC
   ~/.config/fsorter/settings.toml
   #+END_SRC
4. Running fsorter again will sort the current working directory based on the preferences in settings.toml

* Configure
1. Open ~/.config/fsorter/settings.conf in your favourite text editor for example.
   #+BEGIN_SRC
   vim ~/.config/fsorter/settings.conf
   #+END_SRC
2. Here is the basic settings.toml. The name after /home/ will be different then this one it must be your systems username (Running fsorter the first time will generate this for you automatically)
   #+BEGIN_SRC
   [Picture]
   path = "/home/mrfluffy/Pictures/"
   extensions = [".jpg",".jpeg",".png"]
   [Music]
   path = "/home/mrfluffy/Music/"
   extensions = [".mp3",".wav"]
   [Video]
   path = "/home/mrfluffy/Videos/"
   extensions = [".mp4"]
   [Arcive]
   path = "/home/mrfluffy/Documents/Compressed/"
   extensions = [".zip",".rar",".7z"]
    #+END_SRC
3. [Picture] is an example of a category. This can be what ever you want to call it.
4. path = "/home/mrfluffy/Pictures/" is the path you want to save all the files that fall in to this category.
5. extensions = [".jpg",".jpeg",".png"] is all the extensions of files that fall under this category.
